### ISSUE TITLE
Ingredient measurement recognition is a bit too aggressive

### ISSUE THREAD

**Issue by jarcoal** [hillarysanders/recipereader#139]
Right now if I enter the following as an ingredient it will identify both the `1` and `32` as values that should be scaled with the servings:

* 1 (32-ounce) can crushed tomatoes

Obviously it could be written `32 ounces of crushed tomatoes`, but I think the above is clearer to your average home cook.

**Comment by hillarysanders** [comment]
Hey Jarcoal, thanks for the issue! I think the problem was that '-' was not recognized as a spacer between a number and a unit, so the 32-oz. pattern isn't being recognized as an amount that shouldn't be multiplied (because the "number spacer number [spacer?] unit" pattern wasn't catching.

Here's an example of the inconsistency:
http://www.recipestasher.com/recipes/detail/test-1-foo-oz-package,265/
--> servings = 4:
![image](https://cloud.githubusercontent.com/assets/1354094/21661552/7316ae88-d289-11e6-8a39-3c56d2750717.png)
--> servings = 8:
![image](https://cloud.githubusercontent.com/assets/1354094/21661569/8397828c-d289-11e6-9247-09a1c5dde780.png)
All but the second line gets multiplied correctly (although for funzies note that 'chicken' was not pluralized correctly)

--> How to fix? 

I modified the code that searches for '1 32 oz'-like patterns so that it accepts '-' dashes between the second number and the first unit. Should work now! (deployed)
[The commit](https://github.com/hillarysanders/recipereader/commit/a53eee81fd98079f0124de6fd950e0ca6d6aa94b)

New functionality:
servings = 4:
![image](https://cloud.githubusercontent.com/assets/1354094/21662717/5bbc8bd4-d290-11e6-82f2-0438bd68add3.png)
servings = 8:
![image](https://cloud.githubusercontent.com/assets/1354094/21662729/666a958a-d290-11e6-887e-d54ebd443d12.png)

**Comment by jarcoal** [comment]
Working for me now, thanks @hillarysanders !
